version: "3.8"

services:
  tasty.public:
    image: karasovvvvvv2/tasty-public:latest
    build:
      context: frontend/public
      dockerfile: Dockerfile
    container_name: tasty.public
    ports:
      - "5175:5175"
    networks:
      - tasty_network

  tasty.api:
    image: karasovvvvvv2/tasty-api:latest
    build:
      context: backend
      dockerfile: Dockerfile_api
    container_name: tasty.api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/storage/app/public:/app/storage
    networks:
      - tasty_network

  tasty.queue:
    image: karasovvvvvv2/tasty-queue:latest
    build:
      context: backend
      dockerfile: Dockerfile_queue
    container_name: tasty.queue
    depends_on:
      - tasty.redis
    networks:
      - tasty_network

  tasty.nginx:
    image: nginx:latest
    container_name: tasty.nginx
    ports:
      - "8082:80"
    volumes:
      - ./_docker/nginx/conf.d/frontend.conf:/etc/nginx/conf.d/frontend.conf:ro
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tasty.api
      - tasty.queue
      - tasty.public
    networks:
      - tasty_network

networks:
  tasty_network:
    driver: bridge
    name: tasty_network
