services:
  tasty.mysql:
    image: mysql:9
    container_name: tasty.mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - tasty_network

  tasty.phpmyadmin:
    image: phpmyadmin:latest
    container_name: tasty.phpmyadmin
    restart: always
    env_file:
      - .env
    ports:
      - "8081:80"
    networks:
      - tasty_network

  tasty.redis:
    image: redis:latest
    container_name: tasty.redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - tasty_network

  tasty.admin:
    build:
      context: frontend/admin
      dockerfile: Dockerfile
    container_name: tasty.admin
    ports:
      - "5177:5173"
    networks:
      - tasty_network

  tasty.api:
    build:
      context: backend
      dockerfile: Dockerfile_api
    container_name: tasty.api
    ports:
      - "8000:8000"
    depends_on:
      - tasty.mysql
      - tasty.redis
    networks:
      - tasty_network

  tasty.queue:
    build:
      context: backend
      dockerfile: Dockerfile_queue
    container_name: tasty.queue
    depends_on:
      - tasty.mysql
      - tasty.redis
    networks:
      - tasty_network

  tasty.nginx:
    image: nginx:latest
    container_name: tasty.nginx
    ports:
      - "8080:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tasty.api
      - tasty.queue
      - tasty.admin
    networks:
      - tasty_network

networks:
  tasty_network:
    driver: bridge
    name: tasty_network
